### ISSUE TITLE
What does "IL code" mean in Core tools page?

### ISSUE THREAD

**Issue by badersur** [dotnet/core-docs#1057]
In [Driver's section](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/#driver) of .NET Core Command Line Tools topic:

> ### Driver
> The driver is named dotnet. It is the first part of what you invoke. The driver has two responsibilities:
> 1. Executing IL code
> 2. Executing the verb

What does IL code and IL assembly mean? CC: @mairaw

**Comment by svick** [comment]
IL is short for "Intermediate Language", more details are in [the article *What is “managed code”?*](https://docs.microsoft.com/en-us/dotnet/articles/standard/managed-code)

While it's true that `dotnet your.dll` is used to execute an IL assembly, I'm not sure it makes sense to focus on IL here. Maybe, like [the *dotnet* article](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet), this article should talk about "portable apps" instead of "IL code"?

**Comment by badersur** [comment]
Thank you @svick for your clarification. I thought it was a typo because the term "Intermediate Language" didn't appear before. I just noticed the doc's search box now and found your linked article!
