### ISSUE TITLE
Where is "What is .NET?" article?

### ISSUE THREAD

**Issue by badersur** [dotnet/core-docs#1082]
In [.NET Primer](https://docs.microsoft.com/en-us/dotnet/articles/standard/) article, there is this sentence:
> Most of these concepts are defined in the What is .NET? article.

But where is it? Shouldn't we have a link to it?! I can't find it anywhere!

cc: @richlander

**Comment by svick** [comment]
I believe that was supposed to link to [this article](https://github.com/dotnet/core-docs/blob/47d4747556ad0b8c31f32288c6d9bbe3e1174e86/docs/getting-started/what-is-dotnet.md), which was deleted in https://github.com/dotnet/core-docs/pull/609 by @tdykstra (link goes to last version before deletion).

**Comment by tdykstra** [comment]
@svick The doc deleted in #609 was mainly about .NET Core, while the .NET Primer is about .NET platform. We have a [NET Core intro](https://docs.microsoft.com/en-us/dotnet/articles/core/), so there was a lot of overlap and it was decided to retire the deleted doc that you link to. 

@richlander - I think we should delete the .NET Primer section "Key .NET Concepts" because this subject matter is covered by the following "Stroll through .NET" section.  Thoughts?

**Comment by mairaw** [comment]
I agree with you @tdykstra, I think that section can be deleted. PR is coming.
