### ISSUE TITLE
Returns are Missing Table Formatting

### ISSUE THREAD

**Issue by seandebutts** [dotnet/core-docs#196]
In the .NET Framework Library, some methods have parameters and return values in tables. System.Math.Truncate(Double) is an example. In the .NET Core API pages, these parameters and values do not have table formatting and have collapsed together.

Not sure if this is to be solved via overrides or by importing content.

**EXAMPLES:**

**.NET Core**
**https://dotnet.github.io/api/System.Math.html [Scroll down to Truncate(Double)]**
![dot-net-library-table-formatting-is-showing-properly]
(https://cloud.githubusercontent.com/assets/3714242/11671816/b7eab50e-9dbf-11e5-80f2-8e7d61f10c48.JPG)

**.NET Framework Library**
**https://msdn.microsoft.com/en-us/library/c2eabd70(v=vs.110).aspx [Scroll down to table beneath Return Value]**
![dotnet-core-table-lacks-formatting](https://cloud.githubusercontent.com/assets/3714242/11671817/b7eb856a-9dbf-11e5-9858-085082acdf21.JPG)

/cc @blackdwarf @chenkennt @pengbian

**Comment by mairaw** [comment]
This looks a bit better now in docs:
https://docs.microsoft.com/en-us/dotnet/core/api/system.math#System_Math_Truncate_System_Double_
![image](https://cloud.githubusercontent.com/assets/12971179/16778129/616d6124-4821-11e6-9724-b8ffd228ea87.png)

However, since we're still using IntelliSense to generate the docs, there isn't a rich data to identify the table. This needs to be fixed in the content side once we have our final solution for API reference defined (see issue https://github.com/dotnet/core-docs/issues/772).

**Comment by bradygaster** [comment]
This has been fixed. See [here](https://docs.microsoft.com/en-us/dotnet/core/api/system.math#System_Math_Truncate_System_Decimal_)
