### ISSUE TITLE
c-sharp core docs - async

### ISSUE THREAD

**Issue by lazyspark** [dotnet/core-docs#255]
Hi, I would like to contribute to the c-sharp core docs async section. Wanted to take a stackoverflow documentation approach i.e. documentation to surround with examples in the form of gists and walking through top 15 issues from stackoverflow on async. This would be more practical guide than the theory behind async which is important too but not so much useful for beginners. 

As mentioned in the contribution guideline I wanted to create the issue and then follow your recommendations.

**Comment by cartermp** [comment]
We've got async docs written and a big update coming in #214.  Would you like to contribute to that?

**Comment by lazyspark** [comment]
Instead I was wondering if you plan to distill stackoverflow for commonly asked questions and incorporate them in some form in the docs. Also creating gists for all samples so that they can always be tested post doc build. I see that as common problem on msdn is that either there are no samples or the samples have some error. I understand this can be significant undertaking but I am up for it.

**Comment by cartermp** [comment]
Since these docs are still in their infancy it's harder to see, but regarding samples:

- All samples will be buildable and runnable projects in the `/samples` folder
- Once the doc system fully supports this, all sample code in docs will be embedded directly from those buildable projects.  We're hoping to support being able to run those samples in the browser too, but that's a more nebulous long-term goal.

The async docs at #214 are very different from what exists today in MSDN.  The problem with using StackOverflow as the source for information is that most answers are tailored towards that specific question, and it could be easy to have someone approach such a doc and not get the info they needed.  There's some great info posted there, and I can see these docs potentially linking there for more specific scenarios.

I don't think we want to abandon what we've been working on just yet.  A StackOverflow-ification of articles like this doesn't really fit in with our vision for the docs.  Perhaps some of what you're suggesting can be incorporated into what we've got going in #214 already?  We'd love to get more eyes on the content and welcome contributions there.

**Comment by lazyspark** [comment]
Make sense. I would also not like anything to be abandoned from this documentation. I like the documentation. I just was thinking a way to append it with additional constructs like scenarios, examples, questions, etc. For example on properties there would be a question from a typical Java Developer about extension properties :), or there are some very popular questions in SO on C# that are good FAQ for the documentation, just a thought. 

I will go through #214 as a user and if I have anything I will ask on that thread. 

Again, thanks for quick reply. Looking forward to contribute in a positive direction.

**Comment by cartermp** [comment]
Thanks a bunch!  The more feedback, the better.  And definitely feel free to create issues about what you'd like to extend.  @BillWagner is writing a lot of the C# content right now, so there's an opportunity to collaborate with him as well.

**Comment by mairaw** [comment]
#214 was already merged. Is there any scenario we're still missing in the current docs?

**Comment by BillWagner** [comment]
@mairaw I think we've got the major scenarios covered.  The doc from #214 points to @ljw1004 's Channel 9 series, which covers them as well.

**Comment by mairaw** [comment]
I'll close this one then but I'm happy to re-open if we need to address any scenarios we missed.
