### ISSUE TITLE
API reference should not display namespaces of parameter types

### ISSUE THREAD

**Issue by svick** [dotnet/core-docs#313]
For example, the declaration section for [`Enumerable.Zip()`](http://dotnet.github.io/api/System.Linq.Enumerable.html#System_Linq_Enumerable_Zip__3_System_Collections_Generic_IEnumerable___0__System_Collections_Generic_IEnumerable___1__System_Func___0___1___2__) currently looks like this:

`public static Collections.Generic.IEnumerable<TResult> Zip<TFirst, TSecond, TResult>(Collections.Generic.IEnumerable<TFirst> first, Collections.Generic.IEnumerable<TSecond> second, Func<TFirst, TSecond, TResult> resultSelector)`

I believe this would be much easier to read if the namespace for `IEnumerable<T>` was omitted ([just like it is on MSDN](https://msdn.microsoft.com/library/dd267698)):

`public static IEnumerable<TResult> Zip<TFirst, TSecond, TResult>(IEnumerable<TFirst> first, IEnumerable<TSecond> second, Func<TFirst, TSecond, TResult> resultSelector)`

The original declaration is especially confusing, because it doesn't show the whole namespace (including `System.`).

I think the namespace should be also removed from other parts of the API reference: the headings for each method and the Parameters and Returns tables. Especially since those are links, so any possible confusion about the namespace can be cleared by clicking on them.

The same issue applies to other types, like `Task<T>`.

**Comment by cartermp** [comment]
@svick yeah, it seems like it's pulling signatures from the `/ref` folder rather than the source itself.  Clicking on the link doesn't take you to the actual source here, which is another issue.

@chenkennt can weigh in here as well, but I believe that if [this proposal](https://github.com/dotnet/corefx/issues/6518) makes it through then we should be able to rectify this and other related issues.

**Comment by svick** [comment]
This seems to be fixed now.
