### ISSUE TITLE
dependencies, frameworks, ... for libraries

### ISSUE THREAD

**Issue by tmds** [dotnet/core-docs#427]
I was looking for documentation on frameworks+runtimes+dependencies and found this article: http://dotnet.github.io/docs/core-concepts/app-types.html. This topic should also be written for libraries and explain things like:

* How to deal with dependencies when creating a library? Do you also need to add "Microsoft.NETCore.App"? Or should dependencies be handled more fine-grained?
* What frameworks to use when creating a library? E.g. difference between netstandard1.3, netstandard1.5, netcoreapp1.0.
* How to include native dependencies for specific runtimes?
* What preprocessor macros are defined to exclude/include code based on the framework (e.g. #ifdef NET451)?

**Comment by cartermp** [comment]
Some of what you're asking is covered in #412.  I haven't included anything about `netcoreapp` and `Microsoft.NETCore.App` because those are for app development and not library development.  Although there's nothing stopping you from including `Microsoft.NETCore.App` as a dependency in your library, it's not recommended.  There's nothing on native dependencies at this moment because native compilation is still quite a ways off.  For a basic "hello world" console app it *should* work, but once you start incorporating multiple projects there's no guarantee it'll work.

**Comment by tmds** [comment]
Cool. By native I mean: bundle native dlls and so-files for specific platforms with your managed dlls.

**Comment by tmds** [comment]
@cartermp I read and reviewed your article. Together with the app-types it covers all my questions except for the native one. Not sure where it fits in the documentation.

**Comment by cartermp** [comment]
Good to hear!  I'll find out what I can about native deps.  If they're part of the scenarios we want to ship for RC2, I'll include them in the doc.

**Comment by tmds** [comment]
@cartermp all my questions are covered by the article now. thanks

**Comment by cartermp** [comment]
@tmds great!  I'm happy that's the case.  And if something doesn't work right, feel free to yell at me so that it gets updated 😄.
