### ISSUE TITLE
C# tutorials - xml documentation

### ISSUE THREAD

**Issue by stevehoag** [dotnet/core-docs#67]
Show how to document code using XML doc comments.

Tutorials should include one or more code examples, each example should also show expected output and should include an explanation of the code where it isn't obvious. Examples shouldn't be dependent on a specific IDE or target platform.

**Comment by hmobius** [comment]
Hi, If no-one wants to take this, I'd be happy to start working on this. I'm just coming back to coding after a long break, but have been writing \ editing things in the meantime. 

I'm going to suggest that the content is based on the documentation already there in https://msdn.microsoft.com/en-us/library/b2s063f7.aspx but perhaps with a little more about tooling. With docfx, readthedocs etc around, I'm guessing there are tools that aren't sandcastle that can do useful things with the generated XML.

homepage
 / starting_example
 / delimiters and tags
   / <c>
   / <code>
   / etc..
 / generating the XML file
 / tools for using the XML file
   / sandcastle
   / ?
   / write your own : rules for processing the XML file.

**Comment by tsolarin** [comment]
@BillWagner this looks interesting. I'd like to work on this

**Comment by tsolarin** [comment]
@BillWagner that's fine, here's my branch https://github.com/tsolarin/core-docs/blob/xml-doc/docs/csharp/codedoc.md

**Comment by BillWagner** [comment]
@tsolarin I like the start.  I'd like to see samples of each of the tags to help people understand how to use each.

**Comment by tsolarin** [comment]
@BillWagner definitely, was just getting started, will surely include syntax examples and possible attributes

**Comment by tsolarin** [comment]
@BillWagner my first draft is complete, have a look: https://github.com/tsolarin/core-docs/blob/xml-doc/docs/csharp/codedoc.md

**Comment by BillWagner** [comment]
@tsolarin This is a great start.

You've covered all the main tags, and done so quite well.

I have two (related) recommendations for your next draft.

I would order the tags in a logical order of their use rather than alphabetically. I think this applies both to the list and the sections below.  I'd likely start with <Summary> and then <Remarks>. After that, there are a lot of directions you could go, so I'll leave it up to you. I'd expect <Param> and <Returns> to be next to each other though.

After that, make a Pull Request, and we'll do a more detailed content review and then merge.

Thanks again for helping and contributing.

**Comment by tsolarin** [comment]
@BillWagner so in your last comment I assume you made reference to some tags, they're not HTML tags so they don't show up.

**Comment by BillWagner** [comment]
@tsolarin I'm sorry I didn't explain myself well. I meant that you covered all the XML tags that C# uses. 

What I meant by 'ordering the tags' would be to re-order the sections covering each XML tags that C# understands to use the order a reader would want to use them, rather than alphabetically.

I hope that helps.

**Comment by tsolarin** [comment]
Sure
