### ISSUE TITLE
Links to other core-docs topics should be relative

### ISSUE THREAD

**Issue by BillWagner** [dotnet/core-docs#756]
We have a mix of relative and absolute links, even when linking to topics that are part of the same doc site.  

Where the target document is resident in the core-docs repository, we should use relative links. It will facilitate better testing in our local development environment.

/cc @svick

**Comment by mairaw** [comment]
I agree. I also confirmed with VSC that the syntax for API links such as @System.String can be used as a target in links so we should be able to remove all absolute URLs to other core-docs topics.

**Comment by svick** [comment]
When it comes to samples, I'm wondering about user experience: if I'm viewing a sample README on GitHub, and the link is relative, I'm going to arrive at the GiHub rendering of the document, which is not ideal (no TOC, markdown is not rendered exactly right, etc.).

Of course, link that leads to a not ideal rendering of a document is much better than invalid link. But since there are other external links too, maybe verifying external links could be part of build?

**Comment by mairaw** [comment]
I agree @svick. For files that are not really part of the docs site and that users might even open on their computers to use like the samples readme, using the absolute URL might be better.
