### ISSUE TITLE
Windows prerequisites topic questions

### ISSUE THREAD

**Issue by mairaw** [dotnet/core-docs#862]
I have a few questions about the following topic:
https://docs.microsoft.com/en-us/dotnet/articles/core/windows-prerequisites

- We mention Windows 7+, etc. The + sign is not a common convention for international customers so I think we should change to Windows 7 and later versions or something like that. 
- Why do we specifically call out the nano server? Isn't that already covered by Server 2012 R2+?
- I was a bit confused by the VS instructions. Do you need to first install Update 3 to later upgrade to 3.3?

/cc @BillWagner

**Comment by BillWagner** [comment]
The first bullet points makes sense.

I'll defer to @richlander on the second bullet point.

As for the third, I'd welcome any suggestions to make it clearer. The problem is that Update 3.3 is a product update that is installed via the VS Update mechanism. But, only if you already have Update 3 installed. If you install Update 3 now (because you don't already have it), the download automatically applies micro-update 3.3 when you install Update 3.

**Comment by mairaw** [comment]
I'm updating that topic for 1.0.1 and I'll make an attempt to improve these areas at the same time.
